config/routes.rb
Asearcher::Application.routes.draw do

  use_doorkeeper
  scope module: :web do
    root 'welcome#index'
    resources :categories, only: :index
    resource :session, only: %i(new destroy)

    namespace :account do
      resource :category_selection
    end

    namespace :auth do
      resource :github, only: [] do
        get :callback, on: :member
      end
    end
  end

  namespace :web_api do
    resources :html_documents, only: %i[index show]
  end

  namespace :api do
    namespace :v1 do
      resources :stars, only: :create
    end
  end

  namespace :private do
    resource :categories_deploy
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates :external_id, presence: true, uniqueness: true
  acts_as_tree order: 'name'
end

app/models/category_selection.rb
class CategorySelection < ActiveRecord::Base
  extend Enumerize

  belongs_to :category
  belongs_to :user

  validates :user, presence: true
  validates :category, presence: true
  validates :category_id, uniqueness: { scope: :user_id }
  validates :kind, presence: true

  enumerize :kind, in: { selected: 1, excluded: 2 }, default: :selected, scope: true
end

app/models/html_document.rb
class HtmlDocument
  class Star
    include Elastic::ModelMixin

    attribute :user_id, Integer
    attribute :user, User
    attribute :created_at, DateTime
  end

  include Elastic::ModelMixin

  attribute :id
  attribute :url
  attribute :host
  attribute :title
  attribute :description
  attribute :content_in_base64, String, default: ''
  attribute :keywords, Array[String]
  attribute :categories, Array[Category]
  attribute :stars, Array[Star]

end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize
  include UserRepository

  has_many :category_selections, -> { includes(:category).order(:kind, 'categories.name') }

  validates :name, presence: true

  accepts_nested_attributes_for :category_selections, allow_destroy: true

  def guest?
    false
  end
end

app/models/user/github_account.rb
class User::GithubAccount < ActiveRecord::Base
  belongs_to :user

  serialize :auth_hash, OmniAuth::AuthHash

  validates :user, presence: true
  validates :uid, presence: true, uniqueness: true
  validates :auth_hash, presence: true
end

app/models/user/guest.rb
class User::Guest
  def id
    -1
  end

  def selected_categories_with_descendants
    []
  end

  def excluded_categories_with_descendants
    []
  end

  def guest?
    true
  end

  def admin?
    false
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  doorkeeper_for :all

private
  def current_user
    @current_user ||= User.find doorkeeper_token.resource_owner_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UrlHelpers
end

app/controllers/concerns/stored_path.rb
module StoredPath
  extend ActiveSupport::Concern

  included do
    helper_method :stored_cpath
  end

  def stored_cpath
    @stored_path ||= session.delete(:stored_path) || root_path
  end

  def store_request_path!
    session[:stored_path] = request.fullpath
  end
end

app/controllers/concerns/url_helpers.rb
module UrlHelpers
  extend ActiveSupport::Concern

  included do
    %w(github).each do |provider|
      method_name = "auth_#{provider}_cpath"
      define_method method_name do
        "/auth/#{provider}"
      end
      helper_method method_name
    end
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include WebAuthenticationHelper
  include StoredPath

  protect_from_forgery with: :exception
end

app/controllers/web/categories_controller.rb
class Web::CategoriesController < Web::ApplicationController
  def index
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index

  end
end

app/controllers/web_api/application_controller.rb
class WebApi::ApplicationController < ApplicationController
  include WebAuthenticationHelper
  respond_to :json
  layout false

  #before_filter :authenticate_user!

private
  #def authenticate_user!
  #  false unless signed_in?
  #end
end

app/controllers/web_api/html_documents_controller.rb
class WebApi::HtmlDocumentsController < WebApi::ApplicationController
  respond_to :json, :html

  def index
    query = Elastic::HtmlDocument::SearchQuery.new query: params[:q],
                                                   scope: params[:scope],
                                                   offset: params[:offset],
                                                   user: current_user
    documents = query.result
    render json: documents, root: :html_documents
  end

  def show
    query = Elastic::HtmlDocument::FindQuery.new params[:id]
    @document = query.result
    respond_with @document
  end
end

app/controllers/web_api/search_results_controller.rb
class WebApi::SearchResultsController < WebApi::ApplicationController
  def index
    query = Elastic::HtmlDocument::WideSearchQuery.new(params[:q], params[:offset])
    documents = query.result
    render json: documents, root: :html_documents
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories_for_select
    @_categories_for_select ||= _categories_array_from_tree(Category.hash_tree)
  end

private
  def _category_name_for_select(name, depth)
    ['-' * depth, name].select(&:present?).join(' ')
  end

  def _categories_array_from_tree(tree, depth = 0)
    result = []
    tree.each do |node, children|
      result << [_category_name_for_select(node.name, depth), node.id]
      result += _categories_array_from_tree(children, depth + 1)
    end

    result
  end
end

app/helpers/html_document_helper.rb
module HtmlDocumentHelper
  def html_document_content(document)
    html = Base64.decode64(document.content_in_base64)

    #img, a
    tags = %w[section article strong em b i p code pre tt samp kbd var sub sup dfn cite big small address
              hr br div span h1 h2 h3 h4 h5 h6 ul ol li dl dt dd abbr acronym blockquote del ins]
    Readability::Document.new(html, tags: tags).content
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Percolator.io
    = stylesheet_link_tag    "application", media: "all"
    = render 'layouts/rollbar'
    = javascript_include_tag "application"
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
    = csrf_meta_tags
  %body
    = render 'layouts/tagmanager'
    .navbar.navbar-default.navbar-static-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Percolator.io', root_path, class: 'navbar-brand'
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li=link_to 'Readme', 'https://github.com/percolator-io/percolator/blob/master/README.md'
          %ul.nav.navbar-nav.navbar-right
            - if signed_in?
              %li= link_to 'Select categories', edit_account_category_selection_path
              %li.dropdown
                = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to 'Sign out', session_path, method: :delete

            - if signed_out?
              %li= link_to 'Sign in via Github', auth_github_cpath

    .container
      = yield

app/views/web/tags/_form.html.haml
= simple_form_for @tag do |f|
  = f.input :name
  = f.association :parent
  = f.submit class: 'btn btn-primary'